#!/usr/bin/env node

const fs = require('fs');

const commitMsgFile = process.argv[2];
const message = fs.readFileSync(commitMsgFile, 'utf8')
console.log('message:', message);

process.exit(1)
process.exit(0)