name: PR-Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:

  workflow_dispatch:

jobs:
  commit-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check commit messages include Jira tag
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: |
          echo First run!
      - run: git cherry -v master feature/TAG-12345_PR-Check-Action
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: "Verify the name of the PR is well formatted."
        run: echo PR is looking good!
  assign-user:
    runs-on: ubuntu-latest
    steps:
      - name: "Ensure that the author is assigned to the PR."
        run: echo User assigned to the PR!
  pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: "Ensure we have description for this PR."
        run: echo It has a description.